// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwryenhnthmxzlztiamt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3cnllbmhudGhteHpsenRpYW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNDA2MTIsImV4cCI6MjA4NzcxNjYxMn0.X8zWeCNicLoitgreYBeIuF2CBkl702e5vne5FiF4l6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});